runs:
  using: "composite"
  steps:
    - name: Cache Swift packages
      uses: actions/cache@a7833574556fa59680c1b7cb190c1735db73ebf0 # v5
      with:
        path: ~/Library/Developer/Xcode/DerivedData
        key: ${{ runner.os }}-spm-${{ hashFiles('**/Package.resolved') }}
        restore-keys: |
          ${{ runner.os }}-spm-
