runs:
  using: "composite"
  steps:
    - name: Cache Swift packages
      uses: actions/cache@8b402f58fbc84540c8b491a91e594a4576fec3d7 # v5
      with:
        path: ~/Library/Developer/Xcode/DerivedData
        key: ${{ runner.os }}-spm-${{ hashFiles('**/Package.resolved') }}
        restore-keys: |
          ${{ runner.os }}-spm-
