runs:
  using: "composite"
  steps:
    - name: Cache Gradle
      uses: actions/cache@9255dc7a253b0ccc959486e2bca901246202afeb # v5
      with:
        path: |
          ~/.gradle/caches
          ~/.gradle/wrapper
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
        restore-keys: |
          ${{ runner.os }}-gradle-
