inputs:
  working-directory:
    required: false
    default: ./

runs:
  using: "composite"
  steps:
    - name: Cache CocoaPods
      uses: actions/cache@a7833574556fa59680c1b7cb190c1735db73ebf0 # v5
      with:
        path: ${{ inputs.working-directory }}/Pods
        key: ${{ runner.os }}-pods-${{ hashFiles('**/Podfile.lock') }}
        restore-keys: |
          ${{ runner.os }}-pods-
