inputs:
  working-directory:
    required: false
    default: ./

runs:
  using: "composite"
  steps:
    - name: Cache CocoaPods
      uses: actions/cache@9255dc7a253b0ccc959486e2bca901246202afeb # v5
      with:
        path: ${{ inputs.working-directory }}/Pods
        key: ${{ runner.os }}-pods-${{ hashFiles('**/Podfile.lock') }}
        restore-keys: |
          ${{ runner.os }}-pods-
