inputs:
  working-directory:
    required: false
    default: ./

runs:
  using: "composite"
  steps:
    - name: Get Python version
      id: get-python-version
      run: |
        python_version="$(cat .python-version)"
        echo "python-version=$python_version" >> $GITHUB_OUTPUT
      working-directory: ${{ inputs.working-directory }}
      shell: bash
    - name: Cache Python
      uses: actions/cache@a7833574556fa59680c1b7cb190c1735db73ebf0 # v5
      with:
        path: ~/.local/share/virtualenvs
        key: ${{ runner.os }}-python-${{ steps.get-python-version.outputs.python-version }}-pipenv-${{ hashFiles('Pipfile.lock') }}
    - name: Set up Python
      uses: actions/setup-python@83679a892e2d95755f2dac6acb0bfd1e9ac5d548 # v6
      with:
        python-version: ${{ steps.get-python-version.outputs.python-version }}
    - name: Cache pip
      uses: actions/cache@a7833574556fa59680c1b7cb190c1735db73ebf0 # v5
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-
