inputs:
  working-directory:
    required: false
    default: ./

runs:
  using: "composite"
  steps:
    - uses: actions/setup-java@be666c2fcd27ec809703dec50e508c2fdc7f6654 # v5
      with:
        distribution: "temurin"
        java-version: "17"
    # asdf用のバージョン指定ファイルからFlutterのバージョンを読み取り、
    # "-stable" サフィックスを削除したものを環境変数に格納する
    - name: Get Flutter version
      id: get-flutter-version
      run: |
        asdf_flutter_version="$(cat .tool-versions | awk '{print $2}')"
        flutter_version="$(echo $asdf_flutter_version | sed -e 's/-stable//g')"
        echo "flutter-version=$flutter_version" >> $GITHUB_OUTPUT
      working-directory: ${{ inputs.working-directory }}
      shell: bash
    - name: Cache Flutter on Linux
      uses: actions/cache@cdf6c1fa76f9f475f3d7449005a359c84ca0f306 # v5
      if: startsWith(runner.os, 'Linux')
      with:
        path: /opt/hostedtoolcache/flutter
        key: ${{ runner.OS }}-flutter-${{ steps.get-flutter-version.outputs.flutter-version }}
    - name: Cache Flutter on macOS
      uses: actions/cache@cdf6c1fa76f9f475f3d7449005a359c84ca0f306 # v5
      if: startsWith(runner.os, 'macOS')
      with:
        path: /Users/runner/hostedtoolcache/flutter
        key: ${{ runner.OS }}-flutter-${{ steps.get-flutter-version.outputs.flutter-version }}
    - uses: subosito/flutter-action@fd55f4c5af5b953cc57a2be44cb082c8f6635e8e # v2
      with:
        flutter-version: ${{ steps.get-flutter-version.outputs.flutter-version }}
    - name: Enable Swift Package Manager on Flutter
      run: flutter config --enable-swift-package-manager
      shell: bash
    - name: Install FlutterFire CLI
      shell: bash
      run: dart pub global activate flutterfire_cli
